# -*- coding: utf-8 -*-
"""UIDesign.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13hr3biC1Xe5e2z0eKNmbVKpcKIaIdLCU
"""

import pandas as pd
import matplotlib.pyplot as plt
url = 'https://github.com/Tech-Wizz/CSCI-443/blob/main/prototypingNumber.xlsx?raw=true'

df = pd.read_excel(url, index_col=[0])
mn = df.mean()
sd = df.std()
print(mn)
print("+---------------------------------------------------------------------------------------------------------------------------------------------------------+")
print(sd)
print("+---------------------------------------------------------------------------------------------------------------------------------------------------------+")
#print(df.head())

#mn.plot(figsize=(18, 5), rot=90, ylim=0)
#plt.title("Golf App Usability")
#plt.xlabel("Tester")
#plt.ylabel("Score 1-5")
#plt.show()

df.plot.box(figsize=(18, 5), rot=90, ylim=0)
plt.title("Golf App Usability Box Plot")
plt.xlabel("Question")
plt.ylabel("Score 1-5")
plt.show()

df.plot.bar(figsize=(12, 12))
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.title("Golf App Usability")
plt.xlabel("Tester")
plt.ylabel("Score 1-5")
plt.show()